[package]
name = "q-capability-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
tokio-postgres = { version = "0.7", features = ["runtime"] }
serde_json = { workspace = true }

[dev-dependencies]
q-capabilities = { workspace = true }
