/**
 * Artifact emission: bundle (Bun.build), application pack, manifests,
 * contract.json/.d.ts, OpenAPI, contract lock, build report.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import type { ExtractedApp, RouteInfo } from "./extract";
import { hash } from "./extract";

const sha = (s: string) => createHash("sha256").update(s).digest("hex");

// ---------------------------------------------------------------- bundle

export interface BundleResult {
  code: string;
  sourceMap: string | null;
}

export async function bundleApp(
  app: ExtractedApp,
  opts: { sourceMap?: boolean } = {},
): Promise<BundleResult> {
  // synthetic entry: registers handler/policy references from the app modules
  // WITHOUT evaluating any handler/service (COMP-002: Bun.build bundles, never runs)
  const importFiles = [...new Set([...app.routes.map((r) => r.sourceFile), ...app.policies.map((p) => p.sourceFile)])];
  const imports: string[] = [];
  const registers: string[] = [];
  const nsNames = new Map<string, string>();
  importFiles.forEach((f, i) => {
    const ns = `m${i}`;
    nsNames.set(f, ns);
    const rel = relative(app.entryFile, f);
    imports.push(`import * as ${ns} from ${JSON.stringify(rel)};`);
  });
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    registers.push(`__velquRegister(${JSON.stringify(r.id)});`);
  }
  // We register through accessor functions that pull the binding at runtime:
  // the binding name is the exported variable (or default export).
  const accessors: string[] = [];
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    const isDefault = r.bindingName === "__default_export";
    accessors.push(
      `__velquRegister(${JSON.stringify(r.id)}, function (ctx) { return (${ns}.${isDefault ? "default" : r.bindingName}).handle(ctx); });`,
    );
  }
  for (const p of app.policies) {
    const ns = nsNames.get(p.sourceFile)!;
    accessors.push(
      `__velquRegister(${JSON.stringify(p.id)}, function (req) { return (${ns}.${p.bindingName}).check(req); });`,
    );
  }
  const entry = `// @generated by @q/compiler — do not edit\n${imports.join("\n")}\n${accessors.join("\n")}\n`;

  // write synthetic entry to a temp file next to the real entry so relative imports resolve
  const tmpEntry = app.entryFile.replace(/\.ts$/, ".__velqu_entry__.ts");
  const { writeFileSync: wf } = await import("node:fs");
  wf(tmpEntry, entry);
  try {
    const result = await Bun.build({
      entrypoints: [tmpEntry],
      target: "bun",
      format: "esm",
      sourcemap: opts.sourceMap === false ? "none" : "linked",
      minify: false, // keep readable + deterministic
    });
    if (!result.success) {
      const msgs = result.logs.map((l) => String(l)).join("\n");
      throw new Error(`bundle failed:\n${msgs}`);
    }
    const out = result.outputs[0];
    const code = await out.text();
    let sourceMap: string | null = null;
    const mapOut = result.outputs.find((o) => o.path.endsWith(".js.map") || o.kind === "sourcemap");
    if (mapOut) sourceMap = await mapOut.text();
    else if (opts.sourceMap !== false) {
      // "linked" emits .map next to output; fetch by convention
      try {
        const mapPath = out.path + ".map";
        sourceMap = await Bun.file(mapPath).text();
      } catch {
        sourceMap = null;
      }
    }
    return { code, sourceMap };
  } finally {
    const { unlinkSync } = await import("node:fs");
    try {
      unlinkSync(tmpEntry);
    } catch {}
  }
}

function relative(from: string, to: string): string {
  // both absolute-ish repo paths; emit a relative import from entry dir
  const { dirname, relative: rel } = require("node:path") as typeof import("node:path");
  let r = rel(dirname(from), to).replace(/\\/g, "/");
  if (!r.startsWith(".")) r = "./" + r;
  return r.replace(/\.ts$/, ".ts");
}

// ---------------------------------------------------------------- IR → pack structures

function segsFor(path: string): Array<{ kind: string; value: string }> {
  return path
    .split("/")
    .filter(Boolean)
    .map((s) =>
      s.startsWith(":")
        ? { kind: "param", value: s.slice(1) }
        : s.startsWith("*")
          ? { kind: "wildcard", value: "" }
          : { kind: "static", value: s },
    );
}

export function schemaRegistry(app: ExtractedApp): Record<string, unknown> {
  const reg: Record<string, unknown> = {};
  const put = (key: string, ir: Record<string, unknown> | null) => {
    if (ir) reg[key] = ir;
  };
  for (const r of app.routes) {
    put(`sch:${r.id}.params`, r.paramsIr);
    put(`sch:${r.id}.query`, r.queryIr);
    put(`sch:${r.id}.body`, r.bodyIr);
  }
  return reg;
}

/** Rust-canonical: routes keep field order, schema registry keys sorted, IR maps inside sorted (properties). */
function rustCanonical(routes: unknown[], schemas: Record<string, unknown>, policies: unknown, capabilities: string[]): string {
  const sortIR = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(sortIR);
    if (v && typeof v === "object") {
      const o = v as Record<string, unknown>;
      if ("kind" in o) {
        const out: Record<string, unknown> = {};
        for (const k of Object.keys(o)) out[k] = k === "properties" ? sortProps(o[k]) : sortIR(o[k]);
        return out;
      }
      const out: Record<string, unknown> = {};
      for (const k of Object.keys(o).sort()) out[k] = sortIR(o[k]);
      return out;
    }
    return v;
  };
  const sortProps = (v: unknown): Record<string, unknown> => {
    const o = v as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(o).sort()) out[k] = sortIR(o[k]);
    return out;
  };
  const schemasSorted: Record<string, unknown> = {};
  for (const k of Object.keys(schemas).sort()) schemasSorted[k] = sortIR(schemas[k]);
  return JSON.stringify({ routes, schemas: schemasSorted, policies, capabilities });
}

export function buildPack(
  app: ExtractedApp,
  bundle: BundleResult,
  meta: { typescriptVersion: string; compilerVersion: string },
): { packJson: string; pack: Record<string, unknown> } {
  const schemas = schemaRegistry(app);
  const policyPacks: Record<string, unknown> = {};
  for (const p of app.policies) {
    policyPacks[p.id] = {
      id: p.id,
      handler: p.id,
      declaredStatuses: p.declaredStatuses,
      provides: "session",
    };
  }
  const capabilities = [...new Set(app.routes.flatMap((r) => r.capabilities))].filter((c) => c === "timer");

  const packRoutes = app.routes.map((r) => ({
    id: r.id,
    moduleId: r.moduleId,
    method: r.method,
    path: r.path,
    pathSegments: segsFor(r.path),
    handler: r.id,
    policy: r.policyId ?? null,
    params: r.paramsIr ? { schema: `sch:${r.id}.params`, coerce: "path", contentType: null, limitBytes: 0 } : null,
    query: r.queryIr ? { schema: `sch:${r.id}.query`, coerce: "query", contentType: null, limitBytes: 0 } : null,
    body: r.bodyIr
      ? { schema: `sch:${r.id}.body`, coerce: null, contentType: "application/json", limitBytes: 65536 }
      : null,
    headers: null,
    responses: Object.fromEntries(
      Object.entries(r.responses).map(([k, v]) => [k, { schema: null, strategy: v.strategy, problem: v.problem ?? null }]),
    ),
    validationStrategy: "native",
    nativeLiveness: r.liveness,
    security: r.policyId ? [{ scheme: "bearer", header: "authorization", problemStatus: 401 }] : [],
    capabilities: r.capabilities,
    deadlineMs: 5000,
  }));
  const handlerTable: Record<string, string> = {};
  for (const r of app.routes) handlerTable[r.id] = r.id;
  for (const p of app.policies) handlerTable[p.id] = p.id;

  const canonical = rustCanonical(packRoutes, schemas, policyPacks, capabilities);
  const pack = {
    formatVersion: 1,
    kind: "velqu.qpack",
    runtimeAbi: 1,
    engine: { name: "quickjs-ng", version: "0.15.1", binding: "rquickjs-0.12.2" },
    schemaIrVersion: 1,
    contractVersion: 1,
    contractHash: sha(canonical).slice(0, 32),
    builtBy: { compiler: meta.compilerVersion, typescript: meta.typescriptVersion, bun: Bun.version },
    appId: app.appId,
    modules: app.modules,
    entry: "app.js",
    bundle: bundle.code,
    sourceMap: bundle.sourceMap,
    routes: packRoutes,
    schemas,
    policies: policyPacks,
    capabilities,
    handlerTable,
    integrity: { algorithm: "sha256", bundleSha256: sha(bundle.code), routesSha256: sha(canonical) },
  };
  return { packJson: JSON.stringify(pack), pack };
}

// ---------------------------------------------------------------- contract + d.ts + openapi

export function tsTypeOfIr(ir: Record<string, unknown>): string {
  switch (ir.kind) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "literal": return JSON.stringify(ir.value);
    case "enum": return (ir.values as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
    case "optional": return tsTypeOfIr(ir.inner as Record<string, unknown>);
    case "nullable": return `${tsTypeOfIr(ir.inner as Record<string, unknown>)} | null`;
    case "array": return `Array<${tsTypeOfIr(ir.items as Record<string, unknown>)}>`;
    case "object": {
      const props = ir.properties as Record<string, Record<string, unknown>>;
      const req = ir.required as string[];
      const fields = Object.entries(props).map(([k, v]) =>
        req.includes(k) ? `${k}: ${tsTypeOfIr(v)}` : `${k}?: ${tsTypeOfIr(v)}`,
      );
      return `{ ${fields.join("; ")} }`;
    }
    case "union":
      return (ir.members as Record<string, unknown>[]).map(tsTypeOfIr).join(" | ");
    default:
      return "unknown";
  }
}

export function contractFor(app: ExtractedApp): Record<string, unknown> {
  const routes: Record<string, unknown> = {};
  for (const r of app.routes) {
    const responses: Record<string, unknown> = {};
    for (const [status, decl] of Object.entries(r.responses)) {
      if (decl.problem) {
        responses[status] = { title: "string" }; // problem shape placeholder
      } else {
        responses[status] = "{}"; // replaced by tsType below when schema known
      }
    }
    routes[r.id] = {
      path: r.path,
      method: r.method,
      params: r.paramsIr ? tsTypeOfIr(r.paramsIr) : "Record<string, never>",
      query: r.queryIr ? tsTypeOfIr(r.queryIr) : "Record<string, never>",
      body: r.bodyIr ? tsTypeOfIr(r.bodyIr) : "undefined",
      responses: Object.keys(r.responses),
      security: r.policyId ?? undefined,
    };
  }
  return routes;
}

export function contractDts(app: ExtractedApp, contractHash: string): string {
  const lines: string[] = [
    "// @generated by @q/compiler — published compact contract (TRT-006)",
    "// Client repositories import ONLY this file; never server source.",
    'import type { RouteContract } from "@q/contract";',
    "",
    `export interface Api {`,
  ];
  for (const r of app.routes) {
    const respTypes = Object.entries(r.responses).map(([status]) => {
      if (status === "422") return `{ errors: { path: string; code: string; message: string }[]; title: string }`;
      if (status === "401") return `{ title: string }`;
      if (status === "404") return `{ title: string }`;
      return "{}";
    });
    const respTs = Object.entries(r.responses).map(([status], i) => `  ${status}: ${respTypes[i] === "{}" ? successTypeOf(r) : respTypes[i]}`);
    lines.push(
      `  "${r.id}": RouteContract<`,
      `    "${r.path}",`,
      `    "${r.method}",`,
      `    ${r.paramsIr ? tsTypeOfIr(r.paramsIr) : "Record<string, never>"},`,
      `    ${r.queryIr ? tsTypeOfIr(r.queryIr) : "Record<string, never>"},`,
      `    ${r.bodyIr ? tsTypeOfIr(r.bodyIr) : "undefined"},`,
      `    {`,
      ...respTs.map((t) => `      ${t},`),
      `  }>;`,
    );
  }
  lines.push("};", "", `export const contractHash = "${contractHash}";`, "");
  return lines.join("\n");
}

function successTypeOf(r: RouteInfo): string {
  // success (2xx) bodies: derive from response schema? we didn't store success IR;
  // use the response map's first 2xx schema via route extraction (params-style IR not kept)
  return "Record<string, unknown>";
}

export function openapiFor(app: ExtractedApp): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  const components: Record<string, Record<string, unknown>> = {};
  const irToSchema = (ir: Record<string, unknown> | null, name: string): unknown => {
    if (!ir) return undefined;
    const conv = (v: Record<string, unknown>): Record<string, unknown> => {
      const out: Record<string, unknown> = { type: v.kind === "integer" || v.kind === "number" ? v.kind === "integer" ? "integer" : "number" : v.kind };
      if (v.kind === "string") {
        if (v.minLength !== undefined) out.minLength = v.minLength;
        if (v.maxLength !== undefined) out.maxLength = v.maxLength;
        if (v.pattern !== undefined) out.pattern = v.pattern;
        if (v.format !== undefined) out.format = v.format;
      }
      if (v.kind === "integer" || v.kind === "number") {
        if (v.minimum !== undefined) out.minimum = v.minimum;
        if (v.maximum !== undefined) out.maximum = v.maximum;
      }
      if (v.kind === "array") out.items = conv(v.items as Record<string, unknown>);
      if (v.kind === "enum") { out.type = "string"; out.enum = v.values; }
      if (v.kind === "literal") { out.type = typeof v.value; out.enum = [v.value]; }
      if (v.kind === "optional" || v.kind === "nullable") return conv(v.inner as Record<string, unknown>);
      if (v.kind === "object") {
        out.type = "object";
        const props: Record<string, unknown> = {};
        for (const [k, p] of Object.entries(v.properties as Record<string, Record<string, unknown>>)) {
          props[k] = conv(p);
        }
        out.properties = props;
        out.required = v.required;
        out.additionalProperties = false;
      }
      return out;
    };
    const schema = conv(ir);
    components[name] = { ...schema } as Record<string, unknown>;
    return { $ref: `#/components/schemas/${name}` };
  };

  for (const r of app.routes) {
    const params = (r.path.match(/:[A-Za-z]+/g) ?? []).map((p) => p.slice(1));
    const op: Record<string, unknown> = {
      operationId: r.id,
      responses: Object.fromEntries(
        Object.entries(r.responses).map(([status, decl]) => [
          status,
          {
            description: decl.problem ? `problem: ${decl.problem}` : "success",
            content: decl.problem ? undefined : { "application/json": {} },
          },
        ]),
      ),
    };
    if (params.length || r.paramsIr) {
      op.parameters = params.map((p) => ({
        name: p,
        in: "path",
        required: true,
        schema: { type: "string" },
      }));
    }
    if (r.queryIr) {
      op.parameters = [
        ...((op.parameters as unknown[]) ?? []),
        ...Object.keys((r.queryIr as { properties?: Record<string, unknown> }).properties ?? {}).map((k) => ({
          name: k,
          in: "query",
          required: ((r.queryIr as { required?: string[] }).required ?? []).includes(k),
          schema: { type: "string" },
        })),
      ];
    }
    if (r.bodyIr) {
      op.requestBody = {
        required: true,
        content: { "application/json": { schema: irToSchema(r.bodyIr, `${r.id}.body`) } },
      };
    }
    if (r.policyId) op.security = [{ bearerAuth: [] }];
    const oaPath = r.path.replace(/:([A-Za-z]+)/g, "{$1}");
    (paths[oaPath] ??= {})[r.method.toLowerCase()] = op;
  }
  return {
    openapi: "3.1.0",
    info: { title: app.appId, version: "0.1.0" },
    paths,
    components: {
      schemas: components,
      securitySchemes: app.policies.length ? { bearerAuth: { type: "http", scheme: "bearer" } } : undefined,
    },
  };
}

// ---------------------------------------------------------------- semantic diff

export interface DiffEntry {
  routeId: string;
  kind: "breaking" | "compatible" | "policy-sensitive";
  change: string;
}

export function diffContracts(current: Record<string, unknown>, lock: Record<string, unknown>): DiffEntry[] {
  const out: DiffEntry[] = [];
  const cur = current.routes as Record<string, Record<string, unknown>>;
  const prev = lock.routes as Record<string, Record<string, unknown>>;
  for (const [id, route] of Object.entries(cur)) {
    if (!prev[id]) {
      out.push({ routeId: id, kind: "compatible", change: "route added" });
      continue;
    }
    const p = prev[id];
    if (p.path !== route.path) out.push({ routeId: id, kind: "breaking", change: `path changed ${p.path} → ${route.path}` });
    if (p.method !== route.method) out.push({ routeId: id, kind: "breaking", change: `method changed ${p.method} → ${route.method}` });
    const prevStatuses = Object.keys((p.responses ?? {}) as Record<string, unknown>);
    const curStatuses = Object.keys((route.responses ?? {}) as Record<string, unknown>);
    for (const s of prevStatuses) if (!curStatuses.includes(s)) out.push({ routeId: id, kind: "breaking", change: `status ${s} removed` });
    for (const s of curStatuses) if (!prevStatuses.includes(s)) out.push({ routeId: id, kind: "compatible", change: `status ${s} added` });
    if ((p.security ?? null) !== (route.security ?? null)) {
      out.push({ routeId: id, kind: "policy-sensitive", change: `security changed ${JSON.stringify(p.security ?? null)} → ${JSON.stringify(route.security ?? null)}` });
    }
  }
  for (const id of Object.keys(prev)) if (!cur[id]) out.push({ routeId: id, kind: "breaking", change: "route removed" });
  return out;
}
