/**
 * Artifact emission: bundle (Bun.build), application pack, manifests,
 * contract.json/.d.ts, OpenAPI, contract lock, build report.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import type { ExtractedApp, RouteInfo } from "./extract";
import { hash } from "./extract";

const sha = (s: string) => createHash("sha256").update(s).digest("hex");

// ---------------------------------------------------------------- bundle

export interface BundleResult {
  code: string;
  sourceMap: string | null;
}

export async function bundleApp(
  app: ExtractedApp,
  opts: { sourceMap?: boolean } = {},
): Promise<BundleResult> {
  // synthetic entry: registers handler/policy references from the app modules
  // WITHOUT evaluating any handler/service (COMP-002: Bun.build bundles, never runs)
  const importFiles = [...new Set([...app.routes.map((r) => r.sourceFile), ...app.policies.map((p) => p.sourceFile)])];
  const imports: string[] = [];
  const registers: string[] = [];
  const nsNames = new Map<string, string>();
  importFiles.forEach((f, i) => {
    const ns = `m${i}`;
    nsNames.set(f, ns);
    const rel = relative(app.entryFile, f);
    imports.push(`import * as ${ns} from ${JSON.stringify(rel)};`);
  });
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    registers.push(`__velquRegister(${JSON.stringify(r.id)});`);
  }
  const manifestElements: string[] = [];
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    const isDefault = r.bindingName === "__default_export";
    manifestElements.push(`[${JSON.stringify(r.id)}, 0, function (ctx) { return (${ns}.${isDefault ? "default" : r.bindingName}).handle(ctx); }]`);
  }
  for (const p of app.policies) {
    const ns = nsNames.get(p.sourceFile)!;
    manifestElements.push(`[${JSON.stringify(p.id)}, 1, function (req) { return (${ns}.${p.bindingName}).check(req); }]`);
  }

  // Direct vector dispatch with semantic function manifest (M2.3-r3):
  const entry = `// @generated by @velqu/compiler — do not edit\n${imports.join("\n")}\n\nglobalThis.__velquFunctionManifest = [\n  ${manifestElements.join(",\n  ")}\n];\nglobalThis.__velquFunctions = globalThis.__velquFunctionManifest.map(function (e) { return e[2]; });\n`;

  // write synthetic entry to a temp file next to the real entry so relative imports resolve
  const tmpEntry = app.entryFile.replace(/\.ts$/, ".__velqu_entry__.ts");
  const { writeFileSync: wf } = await import("node:fs");
  wf(tmpEntry, entry);
  try {
    const result = await Bun.build({
      entrypoints: [tmpEntry],
      target: "bun",
      format: "esm",
      sourcemap: opts.sourceMap === false ? "none" : "linked",
      minify: false, // keep readable + deterministic
    });
    if (!result.success) {
      const msgs = result.logs.map((l) => String(l)).join("\n");
      throw new Error(`bundle failed:\n${msgs}`);
    }
    const out = result.outputs[0];
    const code = await out.text();
    let sourceMap: string | null = null;
    const mapOut = result.outputs.find((o) => o.path.endsWith(".js.map") || o.kind === "sourcemap");
    if (mapOut) sourceMap = await mapOut.text();
    else if (opts.sourceMap !== false) {
      // "linked" emits .map next to output; fetch by convention
      try {
        const mapPath = out.path + ".map";
        sourceMap = await Bun.file(mapPath).text();
      } catch {
        sourceMap = null;
      }
    }
    return { code, sourceMap };
  } finally {
    const { unlinkSync } = await import("node:fs");
    try {
      unlinkSync(tmpEntry);
    } catch {}
  }
}

function relative(from: string, to: string): string {
  // both absolute-ish repo paths; emit a relative import from entry dir
  const { dirname, relative: rel } = require("node:path") as typeof import("node:path");
  let r = rel(dirname(from), to).replace(/\\/g, "/");
  if (!r.startsWith(".")) r = "./" + r;
  return r.replace(/\.ts$/, ".ts");
}

// ---------------------------------------------------------------- IR → pack structures

function segsFor(path: string): Array<{ kind: string; value: string }> {
  return path
    .split("/")
    .filter(Boolean)
    .map((s) =>
      s.startsWith(":")
        ? { kind: "param", value: s.slice(1) }
        : s.startsWith("*")
          ? { kind: "wildcard", value: "" }
          : { kind: "static", value: s },
    );
}

export function schemaRegistry(app: ExtractedApp): Record<string, unknown> {
  const reg: Record<string, unknown> = {};
  const put = (key: string, ir: Record<string, unknown> | null) => {
    if (ir) reg[key] = ir;
  };
  for (const r of app.routes) {
    put(`sch:${r.id}.params`, r.paramsIr);
    put(`sch:${r.id}.query`, r.queryIr);
    put(`sch:${r.id}.body`, r.bodyIr);
    for (const [status, decl] of Object.entries(r.responses)) {
      if (decl.ir && !decl.problem) put(`sch:${r.id}.${status}`, decl.ir);
    }
  }
  return reg;
}

/** IR-aware canonical sort matching Rust serde:
 *  - IR nodes ({"kind": tag}) keep declaration field order, only `properties` maps sort
 *  - plain map containers sort by key
 *  - arrays keep order */
function sortIR(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortIR);
  if (v && typeof v === "object") {
    const o = v as Record<string, unknown>;
    if ("kind" in o) {
      const out: Record<string, unknown> = {};
      for (const k of Object.keys(o)) out[k] = k === "properties" ? sortProps(o[k]) : sortIR(o[k]);
      return out;
    }
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(o).sort()) out[k] = sortIR(o[k]);
    return out;
  }
  return v;
}
function sortProps(v: unknown): Record<string, unknown> {
  const o = v as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const k of Object.keys(o).sort()) out[k] = sortIR(o[k]);
  return out;
}

/** Rust-canonical: routes keep field order, schema registry keys sorted, IR maps inside sorted (properties). */
function rustCanonical(
  routes: unknown[],
  schemas: Record<string, unknown>,
  policies: unknown,
  capabilities: string[],
  functions: unknown[],
  schemaManifest: unknown[],
  router: unknown,
): string {
  const schemasSorted: Record<string, unknown> = {};
  for (const k of Object.keys(schemas).sort()) schemasSorted[k] = sortIR(schemas[k]);
  // Rust serializes SchemaDecl.ir with BTreeMap-backed IR (sorted properties);
  // deep-sort each manifest entry's IR the same way
  const manifestSorted = (schemaManifest as Array<Record<string, unknown>>).map((e) => ({
    ...e,
    ir: sortIR(e.ir),
  }));
  return JSON.stringify({
    routes,
    schemas: schemasSorted,
    policies,
    capabilities,
    functions,
    schemaManifest: manifestSorted,
    router,
  });
}

function buildSerializedRouter(routes: Array<{ method: string; pathSegments: Array<{ kind: string; value: string }> }>) {
  const methodMap: Record<string, number> = {
    GET: 0,
    POST: 1,
    PUT: 2,
    PATCH: 3,
    DELETE: 4,
    OPTIONS: 5,
    HEAD: 6,
  };
  const nodes: Array<{
    staticEdges: Array<{ segment: string; targetNode: number }>;
    paramEdge: number | null;
    wildcardEdge: number | null;
    terminal: { methodMask: number; routeByMethod: Array<number | null> } | null;
  }> = [
    { staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null },
  ];

  for (let rIdx = 0; rIdx < routes.length; rIdx++) {
    const r = routes[rIdx];
    let curr = 0;
    for (const seg of r.pathSegments) {
      if (seg.kind === "static") {
        const existing = nodes[curr].staticEdges.find((e) => e.segment === seg.value);
        if (existing) {
          curr = existing.targetNode;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].staticEdges.push({ segment: seg.value, targetNode: next });
          curr = next;
        }
      } else if (seg.kind === "param") {
        if (nodes[curr].paramEdge !== null) {
          curr = nodes[curr].paramEdge!;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].paramEdge = next;
          curr = next;
        }
      } else if (seg.kind === "wildcard") {
        if (nodes[curr].wildcardEdge !== null) {
          curr = nodes[curr].wildcardEdge!;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].wildcardEdge = next;
          curr = next;
        }
      }
    }
    if (!nodes[curr].terminal) {
      nodes[curr].terminal = {
        methodMask: 0,
        routeByMethod: [null, null, null, null, null, null, null],
      };
    }
    const mIdx = methodMap[r.method.toUpperCase()] ?? 0;
    nodes[curr].terminal!.methodMask |= 1 << mIdx;
    nodes[curr].terminal!.routeByMethod[mIdx] = rIdx;
  }
  return { nodes };
}

export function buildPack(
  app: ExtractedApp,
  bundle: BundleResult,
  meta: { typescriptVersion: string; compilerVersion: string },
): { packJson: string; pack: Record<string, unknown> } {
  const schemas = schemaRegistry(app);
  const policyPacks: Record<string, unknown> = {};
  const policyIdMap = new Map<string, number>();
  for (let i = 0; i < app.policies.length; i++) {
    const p = app.policies[i];
    policyIdMap.set(p.id, i);
    policyPacks[p.id] = {
      id: p.id,
      handler: p.id,
      declaredStatuses: p.declaredStatuses,
      provides: "session",
    };
  }
  const capabilities = [...new Set(app.routes.flatMap((r) => r.capabilities))].filter((c) => c === "timer");

  const policyHandlerMap = new Map<string, number>();
  for (let i = 0; i < app.policies.length; i++) {
    policyHandlerMap.set(app.policies[i].id, app.routes.length + i);
  }

  const sortedSchemaKeys = Object.keys(schemas).sort();
  const schemaKeyToId = new Map<string, number>();
  const schemaManifest: Array<{ id: number; key: string; ir: unknown }> = [];
  for (let i = 0; i < sortedSchemaKeys.length; i++) {
    const k = sortedSchemaKeys[i];
    schemaKeyToId.set(k, i);
    schemaManifest.push({
      id: i,
      key: k,
      ir: schemas[k],
    });
  }

  const packRoutes = app.routes.map((r, routeIdx) => {
    const defaultStatus = Object.keys(r.responses).includes("200")
      ? 200
      : Number(Object.keys(r.responses)[0] ?? 200);
    const allowedStatuses = Object.keys(r.responses)
      .map((k) => Number(k))
      .filter((n) => !isNaN(n))
      .sort((a, b) => a - b);
    const responseStrategy = r.responses["200"]?.strategy ?? (Object.values(r.responses)[0]?.strategy ?? "js");

    const paramsSchemaKey = r.paramsIr ? `sch:${r.id}.params` : null;
    const querySchemaKey = r.queryIr ? `sch:${r.id}.query` : null;
    const bodySchemaKey = r.bodyIr ? `sch:${r.id}.body` : null;

    const plan = {
      routeId: routeIdx,
      handlerId: routeIdx,
      policyId: r.policyId ? (policyIdMap.get(r.policyId) ?? null) : null,
      policyHandlerId: r.policyId ? (policyHandlerMap.get(r.policyId) ?? null) : null,
      paramsSchemaId: paramsSchemaKey ? (schemaKeyToId.get(paramsSchemaKey) ?? null) : null,
      querySchemaId: querySchemaKey ? (schemaKeyToId.get(querySchemaKey) ?? null) : null,
      headersSchemaId: null,
      bodySchemaId: bodySchemaKey ? (schemaKeyToId.get(bodySchemaKey) ?? null) : null,
      defaultStatus,
      allowedStatuses,
      fieldNeeds: {
        params: r.paramsIr != null,
        query: r.queryIr != null,
        headers: r.policyId != null,
        body: r.bodyIr != null,
      },
      responseStrategy,
      deadlineMs: 5000,
    };

    return {
      id: r.id,
      moduleId: r.moduleId,
      method: r.method,
      path: r.path,
      pathSegments: segsFor(r.path),
      handler: r.id,
      policy: r.policyId ?? null,
      params: r.paramsIr ? { schema: `sch:${r.id}.params`, coerce: "path", contentType: null, limitBytes: 0 } : null,
      query: r.queryIr ? { schema: `sch:${r.id}.query`, coerce: "query", contentType: null, limitBytes: 0 } : null,
      body: r.bodyIr
        ? { schema: `sch:${r.id}.body`, coerce: null, contentType: "application/json", limitBytes: 65536 }
        : null,
      headers: null,
      responses: Object.fromEntries(
        Object.entries(r.responses).map(([k, v]) => [
          k,
          {
            schema: v.ir && !v.problem ? `sch:${r.id}.${k}` : null,
            strategy: v.strategy,
            problem: v.problem ?? null,
          },
        ]),
      ),
      validationStrategy: "native",
      nativeLiveness: r.liveness,
      security: r.policyId ? [{ scheme: "bearer", header: "authorization", problemStatus: 401 }] : [],
      capabilities: r.capabilities,
      deadlineMs: 5000,
      plan,
    };
  });
  // Numeric current packs carry no legacy handler table (M23R2 gate rule)
  const handlerTable: Record<string, string> = {};

  const functions = [
    ...app.routes.map((r, i) => ({
      id: i,
      key: r.id,
      kind: "route-handler",
    })),
    ...app.policies.map((p, i) => ({
      id: app.routes.length + i,
      key: p.id,
      kind: "policy-handler",
    })),
  ];

  const router = buildSerializedRouter(packRoutes);
  const canonical = rustCanonical(
    packRoutes,
    schemas,
    policyPacks,
    capabilities,
    functions,
    schemaManifest,
    router,
  );

  // M2.3-r3: publicContractHash is stable across internal function manifest reordering.
  // Mirrors Rust public_contract_canonical_json exactly:
  // [routes, schemas(BTreeMap sorted, IR-aware sort), policies(BTreeMap sorted)]
  const policiesPublic: Record<string, unknown> = {};
  for (const k of Object.keys(policyPacks).sort()) policiesPublic[k] = policyPacks[k];
  const schemasPublic: Record<string, unknown> = {};
  for (const k of Object.keys(schemas).sort()) schemasPublic[k] = sortIR(schemas[k]);
  const publicRoutes = packRoutes.map((r) => {
    const responsesSorted: Record<string, unknown> = {};
    for (const k of Object.keys(r.responses).sort()) responsesSorted[k] = r.responses[k];
    return {
      id: r.id,
      method: r.method,
      path: r.path,
      params: r.params?.schema ?? null,
      query: r.query?.schema ?? null,
      body: r.body?.schema ?? null,
      responses: responsesSorted,
      security: r.security,
    };
  });
  const publicContractCanonical = JSON.stringify([publicRoutes, schemasPublic, policiesPublic]);
  const contractHash = sha(publicContractCanonical).slice(0, 32);

  const pack = {
    formatVersion: 1,
    kind: "velqu.qpack",
    runtimeAbi: 1,
    engine: { name: "quickjs-ng", version: "0.15.1", binding: "rquickjs-0.12.2" },
    schemaIrVersion: 1,
    contractVersion: 1,
    contractHash,
    builtBy: { compiler: meta.compilerVersion, typescript: meta.typescriptVersion, bun: Bun.version },
    appId: app.appId,
    modules: app.modules,
    entry: "app.js",
    bundle: bundle.code,
    sourceMap: bundle.sourceMap,
    routes: packRoutes,
    schemas,
    policies: policyPacks,
    capabilities,
    functions,
    schemaManifest,
    router,
    handlerTable,
    integrity: { algorithm: "sha256", bundleSha256: sha(bundle.code), routesSha256: sha(canonical) },
  };
  return { packJson: JSON.stringify(pack), pack };
}

// ---------------------------------------------------------------- contract + d.ts + openapi

export function tsTypeOfIr(ir: Record<string, unknown>): string {
  switch (ir.kind) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "literal": return JSON.stringify(ir.value);
    case "enum": return (ir.values as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
    case "optional": return tsTypeOfIr(ir.inner as Record<string, unknown>);
    case "nullable": return `${tsTypeOfIr(ir.inner as Record<string, unknown>)} | null`;
    case "array": return `Array<${tsTypeOfIr(ir.items as Record<string, unknown>)}>`;
    case "object": {
      const props = ir.properties as Record<string, Record<string, unknown>>;
      const req = ir.required as string[];
      const fields = Object.entries(props).map(([k, v]) =>
        req.includes(k) ? `${k}: ${tsTypeOfIr(v)}` : `${k}?: ${tsTypeOfIr(v)}`,
      );
      return `{ ${fields.join("; ")} }`;
    }
    case "union":
      return (ir.members as Record<string, unknown>[]).map(tsTypeOfIr).join(" | ");
    default:
      return "unknown";
  }
}

export function contractFor(app: ExtractedApp): Record<string, unknown> {
  const routes: Record<string, unknown> = {};
  for (const r of app.routes) {
    const responses: Record<string, unknown> = {};
    for (const [status, decl] of Object.entries(r.responses)) {
      if (decl.problem) {
        responses[status] = { title: "string" }; // problem shape placeholder
      } else {
        responses[status] = "{}"; // replaced by tsType below when schema known
      }
    }
    routes[r.id] = {
      path: r.path,
      method: r.method,
      params: r.paramsIr ? tsTypeOfIr(r.paramsIr) : "Record<string, never>",
      query: r.queryIr ? tsTypeOfIr(r.queryIr) : "Record<string, never>",
      body: r.bodyIr ? tsTypeOfIr(r.bodyIr) : "undefined",
      responses: Object.keys(r.responses),
      security: r.policyId ?? undefined,
    };
  }
  return routes;
}

export function contractDts(app: ExtractedApp, contractHash: string): string {
  const lines: string[] = [
    "// @generated by @velqu/compiler — published compact contract (TRT-006)",
    "// Client repositories import ONLY this file; never server source.",
    'import type { RouteContract } from "@velqu/contract";',
    "",
    `export interface Api {`,
  ];
  for (const r of app.routes) {
    const respTs = Object.entries(r.responses).map(([status, decl]) => {
      if (decl.problem) return problemTypeOf(status);
      if (decl.ir) return tsTypeOfIr(decl.ir);
      return "Record<string, unknown>";
    }).map((t, i) => `  ${Object.keys(r.responses)[i]}: ${t}`);
    lines.push(
      `  "${r.id}": RouteContract<`,
      `    "${r.path}",`,
      `    "${r.method}",`,
      `    ${r.paramsIr ? tsTypeOfIr(r.paramsIr) : "Record<string, never>"},`,
      `    ${r.queryIr ? tsTypeOfIr(r.queryIr) : "Record<string, never>"},`,
      `    ${r.bodyIr ? tsTypeOfIr(r.bodyIr) : "undefined"},`,
      `    {`,
      ...respTs.map((t) => `      ${t},`),
      `  }>;`,
    );
  }
  lines.push("};", "", `export const contractHash = "${contractHash}";`, "");
  return lines.join("\n");
}

function problemTypeOf(status: string): string {
  if (status === "422") return `{ errors: { path: string; code: string; message: string }[]; title: string }`;
  return `{ title: string }`;
}

export function openapiFor(app: ExtractedApp): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  const components: Record<string, Record<string, unknown>> = {};
  const irToSchema = (ir: Record<string, unknown> | null, name: string): unknown => {
    if (!ir) return undefined;
    const conv = (v: Record<string, unknown>): Record<string, unknown> => {
      const out: Record<string, unknown> = { type: v.kind === "integer" || v.kind === "number" ? v.kind === "integer" ? "integer" : "number" : v.kind };
      if (v.kind === "string") {
        if (v.minLength !== undefined) out.minLength = v.minLength;
        if (v.maxLength !== undefined) out.maxLength = v.maxLength;
        if (v.pattern !== undefined) out.pattern = v.pattern;
        if (v.format !== undefined) out.format = v.format;
      }
      if (v.kind === "integer" || v.kind === "number") {
        if (v.minimum !== undefined) out.minimum = v.minimum;
        if (v.maximum !== undefined) out.maximum = v.maximum;
      }
      if (v.kind === "array") out.items = conv(v.items as Record<string, unknown>);
      if (v.kind === "enum") { out.type = "string"; out.enum = v.values; }
      if (v.kind === "literal") { out.type = typeof v.value; out.enum = [v.value]; }
      if (v.kind === "optional" || v.kind === "nullable") return conv(v.inner as Record<string, unknown>);
      if (v.kind === "object") {
        out.type = "object";
        const props: Record<string, unknown> = {};
        for (const [k, p] of Object.entries(v.properties as Record<string, Record<string, unknown>>)) {
          props[k] = conv(p);
        }
        out.properties = props;
        out.required = v.required;
        out.additionalProperties = false;
      }
      return out;
    };
    const schema = conv(ir);
    components[name] = { ...schema } as Record<string, unknown>;
    return { $ref: `#/components/schemas/${name}` };
  };

  for (const r of app.routes) {
    const params = (r.path.match(/:[A-Za-z]+/g) ?? []).map((p) => p.slice(1));
    const op: Record<string, unknown> = {
      operationId: r.id,
      responses: Object.fromEntries(
        Object.entries(r.responses).map(([status, decl]) => [
          status,
          {
            description: decl.problem ? `problem: ${decl.problem}` : "success",
            content:
              decl.ir && !decl.problem
                ? { "application/json": { schema: irToSchema(decl.ir, `${r.id}.resp${status}`) } }
                : undefined,
          },
        ]),
      ),
    };
    if (params.length || r.paramsIr) {
      op.parameters = params.map((p) => ({
        name: p,
        in: "path",
        required: true,
        schema: { type: "string" },
      }));
    }
    if (r.queryIr) {
      op.parameters = [
        ...((op.parameters as unknown[]) ?? []),
        ...Object.keys((r.queryIr as { properties?: Record<string, unknown> }).properties ?? {}).map((k) => ({
          name: k,
          in: "query",
          required: ((r.queryIr as { required?: string[] }).required ?? []).includes(k),
          schema: { type: "string" },
        })),
      ];
    }
    if (r.bodyIr) {
      op.requestBody = {
        required: true,
        content: { "application/json": { schema: irToSchema(r.bodyIr, `${r.id}.body`) } },
      };
    }
    if (r.policyId) op.security = [{ bearerAuth: [] }];
    const oaPath = r.path.replace(/:([A-Za-z]+)/g, "{$1}");
    (paths[oaPath] ??= {})[r.method.toLowerCase()] = op;
  }
  return {
    openapi: "3.1.0",
    info: { title: app.appId, version: "0.1.0" },
    paths,
    components: {
      schemas: components,
      securitySchemes: app.policies.length ? { bearerAuth: { type: "http", scheme: "bearer" } } : undefined,
    },
  };
}

// ---------------------------------------------------------------- semantic diff

export interface DiffEntry {
  routeId: string;
  kind: "breaking" | "compatible" | "policy-sensitive";
  change: string;
}

export function diffContracts(current: Record<string, unknown>, lock: Record<string, unknown>): DiffEntry[] {
  const out: DiffEntry[] = [];
  const cur = current.routes as Record<string, Record<string, unknown>>;
  const prev = lock.routes as Record<string, Record<string, unknown>>;

  for (const [id, route] of Object.entries(cur)) {
    if (!prev[id]) {
      out.push({ routeId: id, kind: "compatible", change: "route added" });
      continue;
    }
    const p = prev[id];
    if (p.path !== route.path) {
      out.push({ routeId: id, kind: "breaking", change: `path changed ${p.path} → ${route.path}` });
    }
    if (p.method !== route.method) {
      out.push({ routeId: id, kind: "breaking", change: `method changed ${p.method} → ${route.method}` });
    }

    // Status codes diff
    const prevResponses = (p.responses ?? {}) as Record<string, unknown>;
    const curResponses = (route.responses ?? {}) as Record<string, unknown>;
    const prevStatuses = Array.isArray(prevResponses) ? prevResponses : Object.keys(prevResponses);
    const curStatuses = Array.isArray(curResponses) ? curResponses : Object.keys(curResponses);

    for (const s of prevStatuses) {
      if (!curStatuses.includes(s)) {
        out.push({ routeId: id, kind: "breaking", change: `response status ${s} removed` });
      }
    }
    for (const s of curStatuses) {
      if (!prevStatuses.includes(s)) {
        const is2xx = Number(s) >= 200 && Number(s) < 300;
        out.push({
          routeId: id,
          kind: is2xx ? "compatible" : "policy-sensitive",
          change: `response status ${s} added`,
        });
      }
    }

    // Security diff
    const prevSec = p.security ?? null;
    const curSec = route.security ?? null;
    if (prevSec !== curSec) {
      if (!prevSec && curSec) {
        out.push({
          routeId: id,
          kind: "breaking",
          change: `security policy added (${JSON.stringify(curSec)}) — requires authentication`,
        });
      } else if (prevSec && !curSec) {
        out.push({
          routeId: id,
          kind: "policy-sensitive",
          change: `security policy removed (${JSON.stringify(prevSec)}) — endpoint became unauthenticated`,
        });
      } else {
        out.push({
          routeId: id,
          kind: "policy-sensitive",
          change: `security policy changed ${JSON.stringify(prevSec)} → ${JSON.stringify(curSec)}`,
        });
      }
    }

    // Input Schema Diff (params, query, body)
    diffSchemaSection(id, "params", p.params as Record<string, unknown> | null, route.params as Record<string, unknown> | null, out, true);
    diffSchemaSection(id, "query", p.query as Record<string, unknown> | null, route.query as Record<string, unknown> | null, out, true);
    diffSchemaSection(id, "body", p.body as Record<string, unknown> | null, route.body as Record<string, unknown> | null, out, true);

    // Response Schema Diff for common 2xx responses
    if (!Array.isArray(prevResponses) && !Array.isArray(curResponses)) {
      for (const s of curStatuses) {
        if (prevStatuses.includes(s) && Number(s) >= 200 && Number(s) < 300) {
          diffSchemaSection(
            id,
            `response.${s}`,
            prevResponses[s] as Record<string, unknown> | null,
            curResponses[s] as Record<string, unknown> | null,
            out,
            false,
          );
        }
      }
    }
  }

  for (const id of Object.keys(prev)) {
    if (!cur[id]) {
      out.push({ routeId: id, kind: "breaking", change: "route removed" });
    }
  }
  return out;
}

function diffSchemaSection(
  routeId: string,
  section: string,
  prev: Record<string, unknown> | null,
  cur: Record<string, unknown> | null,
  out: DiffEntry[],
  isInput: boolean,
) {
  if (!prev && !cur) return;
  if (!prev && cur) {
    const req = (cur.required as string[]) ?? [];
    if (isInput && req.length > 0) {
      out.push({ routeId, kind: "breaking", change: `${section}: added required schema with required fields [${req.join(", ")}]` });
    } else {
      out.push({ routeId, kind: "compatible", change: `${section}: schema added` });
    }
    return;
  }
  if (prev && !cur) {
    out.push({ routeId, kind: isInput ? "compatible" : "breaking", change: `${section}: schema removed` });
    return;
  }
  if (prev && cur) {
    diffSchemaTypes(routeId, section, prev, cur, out, isInput);
  }
}

function diffSchemaTypes(
  routeId: string,
  section: string,
  prev: Record<string, unknown>,
  cur: Record<string, unknown>,
  out: DiffEntry[],
  isInput: boolean,
) {
  if (prev.kind !== cur.kind) {
    out.push({
      routeId,
      kind: "breaking",
      change: `${section}: type kind changed ${prev.kind} → ${cur.kind}`,
    });
    return;
  }
  if (prev.kind === "object" && cur.kind === "object") {
    const prevProps = (prev.properties ?? {}) as Record<string, Record<string, unknown>>;
    const curProps = (cur.properties ?? {}) as Record<string, Record<string, unknown>>;
    const prevReq = new Set((prev.required as string[]) ?? []);
    const curReq = new Set((cur.required as string[]) ?? []);

    for (const [propName, curProp] of Object.entries(curProps)) {
      if (!prevProps[propName]) {
        const isRequired = curReq.has(propName);
        if (isInput) {
          out.push({
            routeId,
            kind: isRequired ? "breaking" : "compatible",
            change: `${section}.${propName}: ${isRequired ? "required" : "optional"} field added to input`,
          });
        } else {
          out.push({
            routeId,
            kind: "compatible",
            change: `${section}.${propName}: field added to response`,
          });
        }
      } else {
        const prevProp = prevProps[propName];
        if (isInput && !prevReq.has(propName) && curReq.has(propName)) {
          out.push({
            routeId,
            kind: "breaking",
            change: `${section}.${propName}: optional input field became required`,
          });
        }
        diffSchemaTypes(routeId, `${section}.${propName}`, prevProp, curProp, out, isInput);
      }
    }

    for (const propName of Object.keys(prevProps)) {
      if (!curProps[propName]) {
        if (isInput) {
          out.push({ routeId, kind: "compatible", change: `${section}.${propName}: input field removed` });
        } else {
          out.push({ routeId, kind: "breaking", change: `${section}.${propName}: response field removed` });
        }
      }
    }
  } else if (prev.kind === "array" && cur.kind === "array") {
    if (prev.items && cur.items) {
      diffSchemaTypes(routeId, `${section}[]`, prev.items as Record<string, unknown>, cur.items as Record<string, unknown>, out, isInput);
    }
  }
}
