/**
 * Artifact emission: bundle (Bun.build), application pack, manifests,
 * contract.json/.d.ts, OpenAPI, contract lock, build report.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import type { ExtractedApp, RouteInfo } from "./extract";
import { hash } from "./extract";
import { featuresOf } from "@velqu/schema";
import { selectRouteStrategies } from "./strategy";

const sha = (s: string) => createHash("sha256").update(s).digest("hex");

// ---------------------------------------------------------------- bundle

export interface BundleResult {
  code: string;
  sourceMap: string | null;
}

export async function bundleApp(
  app: ExtractedApp,
  opts: { sourceMap?: boolean } = {},
): Promise<BundleResult> {
  // synthetic entry: registers handler/policy references from the app modules
  // WITHOUT evaluating any handler/service (COMP-002: Bun.build bundles, never runs)
  const importFiles = [...new Set([...app.routes.map((r) => r.sourceFile), ...app.policies.map((p) => p.sourceFile)])];
  const imports: string[] = [];
  const registers: string[] = [];
  const nsNames = new Map<string, string>();
  importFiles.forEach((f, i) => {
    const ns = `m${i}`;
    nsNames.set(f, ns);
    const rel = relative(app.entryFile, f);
    imports.push(`import * as ${ns} from ${JSON.stringify(rel)};`);
  });
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    registers.push(`__velquRegister(${JSON.stringify(r.id)});`);
  }
  const manifestElements: string[] = [];
  for (const r of app.routes) {
    const ns = nsNames.get(r.sourceFile)!;
    const isDefault = r.bindingName === "__default_export";
    manifestElements.push(`[${JSON.stringify(r.id)}, 0, function (ctx) { return (${ns}.${isDefault ? "default" : r.bindingName}).handle(ctx); }]`);
  }
  for (const p of app.policies) {
    const ns = nsNames.get(p.sourceFile)!;
    manifestElements.push(`[${JSON.stringify(p.id)}, 1, function (req) { return (${ns}.${p.bindingName}).check(req); }]`);
  }

  // Direct vector dispatch with semantic function manifest (M2.3-r3):
  const entry = `// @generated by @velqu/compiler — do not edit\n${imports.join("\n")}\n\nglobalThis.__velquFunctionManifest = [\n  ${manifestElements.join(",\n  ")}\n];\nglobalThis.__velquFunctions = globalThis.__velquFunctionManifest.map(function (e) { return e[2]; });\n`;

  // write synthetic entry to a temp file next to the real entry so relative imports resolve
  const tmpEntry = app.entryFile.replace(/\.ts$/, ".__velqu_entry__.ts");
  const { writeFileSync: wf } = await import("node:fs");
  wf(tmpEntry, entry);
  try {
    const result = await Bun.build({
      entrypoints: [tmpEntry],
      target: "bun",
      format: "esm",
      sourcemap: opts.sourceMap === false ? "none" : "linked",
      minify: false, // keep readable + deterministic
    });
    if (!result.success) {
      const msgs = result.logs.map((l) => String(l)).join("\n");
      throw new Error(`bundle failed:\n${msgs}`);
    }
    const out = result.outputs[0];
    const code = await out.text();
    let sourceMap: string | null = null;
    const mapOut = result.outputs.find((o) => o.path.endsWith(".js.map") || o.kind === "sourcemap");
    if (mapOut) sourceMap = await mapOut.text();
    else if (opts.sourceMap !== false) {
      // "linked" emits .map next to output; fetch by convention
      try {
        const mapPath = out.path + ".map";
        sourceMap = await Bun.file(mapPath).text();
      } catch {
        sourceMap = null;
      }
    }
    return { code, sourceMap };
  } finally {
    const { unlinkSync } = await import("node:fs");
    try {
      unlinkSync(tmpEntry);
    } catch {}
  }
}

function relative(from: string, to: string): string {
  // both absolute-ish repo paths; emit a relative import from entry dir
  const { dirname, relative: rel } = require("node:path") as typeof import("node:path");
  let r = rel(dirname(from), to).replace(/\\/g, "/");
  if (!r.startsWith(".")) r = "./" + r;
  return r.replace(/\.ts$/, ".ts");
}

// ---------------------------------------------------------------- IR → pack structures

function segsFor(path: string): Array<{ kind: string; value: string }> {
  return path
    .split("/")
    .filter(Boolean)
    .map((s) =>
      s.startsWith(":")
        ? { kind: "param", value: s.slice(1) }
        : s.startsWith("*")
          ? { kind: "wildcard", value: "" }
          : { kind: "static", value: s },
    );
}

export function schemaRegistry(app: ExtractedApp): Record<string, unknown> {
  const reg: Record<string, unknown> = {};
  const put = (key: string, ir: Record<string, unknown> | null) => {
    if (ir) reg[key] = ir;
  };
  for (const r of app.routes) {
    put(`sch:${r.id}.params`, r.paramsIr);
    put(`sch:${r.id}.query`, r.queryIr);
    put(`sch:${r.id}.body`, r.bodyIr);
    for (const [status, decl] of Object.entries(r.responses)) {
      if (decl.ir && !decl.problem) put(`sch:${r.id}.${status}`, decl.ir);
    }
  }
  return reg;
}

/**
 * Canonical JSON form (M25-001-C, ADR-0023): every object's keys are sorted
 * recursively (code-unit order), arrays keep their order. Mirrors
 * `q_schema_runtime::canonical_value` — both sides hash the same canonical
 * string regardless of source literal field order.
 */
function sortIR(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortIR);
  if (v && typeof v === "object") {
    const o = v as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(o).sort()) out[k] = sortIR(o[k]);
    return out;
  }
  return v;
}

/** Rust-canonical: the whole execution-graph view passes through sortIR. */
function rustCanonical(
  routes: unknown[],
  schemas: Record<string, unknown>,
  policies: unknown,
  capabilities: string[],
  functions: unknown[],
  schemaManifest: unknown[],
  policyManifest: unknown[],
  router: unknown,
): string {
  return JSON.stringify(
    sortIR({
      routes,
      schemas,
      policies,
      capabilities,
      functions,
      schemaManifest,
      policyManifest,
      router,
    }),
  );
}

function buildSerializedRouter(routes: Array<{ method: string; pathSegments: Array<{ kind: string; value: string }> }>) {
  const methodMap: Record<string, number> = {
    GET: 0,
    POST: 1,
    PUT: 2,
    PATCH: 3,
    DELETE: 4,
    OPTIONS: 5,
    HEAD: 6,
  };
  const nodes: Array<{
    staticEdges: Array<{ segment: string; targetNode: number }>;
    paramEdge: number | null;
    wildcardEdge: number | null;
    terminal: { methodMask: number; routeByMethod: Array<number | null> } | null;
  }> = [
    { staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null },
  ];

  for (let rIdx = 0; rIdx < routes.length; rIdx++) {
    const r = routes[rIdx];
    let curr = 0;
    for (const seg of r.pathSegments) {
      if (seg.kind === "static") {
        const existing = nodes[curr].staticEdges.find((e) => e.segment === seg.value);
        if (existing) {
          curr = existing.targetNode;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].staticEdges.push({ segment: seg.value, targetNode: next });
          curr = next;
        }
      } else if (seg.kind === "param") {
        if (nodes[curr].paramEdge !== null) {
          curr = nodes[curr].paramEdge!;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].paramEdge = next;
          curr = next;
        }
      } else if (seg.kind === "wildcard") {
        if (nodes[curr].wildcardEdge !== null) {
          curr = nodes[curr].wildcardEdge!;
        } else {
          const next = nodes.length;
          nodes.push({ staticEdges: [], paramEdge: null, wildcardEdge: null, terminal: null });
          nodes[curr].wildcardEdge = next;
          curr = next;
        }
      }
    }
    if (!nodes[curr].terminal) {
      nodes[curr].terminal = {
        methodMask: 0,
        routeByMethod: [null, null, null, null, null, null, null],
      };
    }
    const mIdx = methodMap[r.method.toUpperCase()] ?? 0;
    nodes[curr].terminal!.methodMask |= 1 << mIdx;
    nodes[curr].terminal!.routeByMethod[mIdx] = rIdx;
  }
  return { nodes };
}


/** M26-002-A: sha256 hex via Bun — mirrors q-pack's hex(&Sha256::digest()). */
function sha256Hex(input: string): string {
  return new Bun.CryptoHasher("sha256").update(input).digest("hex");
}

/** Runtime identity tuple hash — MUST equal q_pack::runtime_build_hash(). */
function runtimeBuildHash(): string {
  return sha256Hex("abi=1:engine=quickjs-ng:version=0.15.1:rquickjs=0.12.2:binding=rquickjs-0.12.2");
}

/** Capability-set hash — MUST equal q_pack::capability_hash(). */
function capabilitySetHash(caps: string[]): string {
  return sha256Hex([...caps].sort().join("\n"));
}

export function buildPack(
  app: ExtractedApp,
  bundle: BundleResult,
  meta: { typescriptVersion: string; compilerVersion: string },
): { packJson: string; pack: Record<string, unknown> } {
  const schemas = schemaRegistry(app);
  const policyPacks: Record<string, unknown> = {};
  // Dense policy manifest: sorted by key (BTreeMap order) → PolicyId = index
  const sortedPolicyKeys = [...new Set(app.policies.map((p) => p.id))].sort();
  const policyIdMap = new Map<string, number>();
  for (let i = 0; i < sortedPolicyKeys.length; i++) {
    policyIdMap.set(sortedPolicyKeys[i], i);
  }
  const policyManifest: Array<{ id: number; key: string; handlerId: number }> = [];
  for (const key of sortedPolicyKeys) {
    const p = app.policies.find((x) => x.id === key)!;
    policyPacks[key] = {
      id: p.id,
      handler: p.id,
      declaredStatuses: p.declaredStatuses,
      provides: "session",
    };
    policyManifest.push({
      id: policyIdMap.get(key)!,
      key,
      handlerId: policyHandlerIndex(app, key),
    });
  }
  const capabilities = [...new Set(app.routes.flatMap((r) => r.capabilities))].filter((c) => c === "timer");

  const policyHandlerMap = new Map<string, number>();
  for (let i = 0; i < app.policies.length; i++) {
    policyHandlerMap.set(app.policies[i].id, app.routes.length + i);
  }

  function policyHandlerIndex(app: ExtractedApp, policyId: string): number {
    const idx = app.policies.findIndex((p) => p.id === policyId);
    return app.routes.length + idx;
  }

  const sortedSchemaKeys = Object.keys(schemas).sort();
  const schemaKeyToId = new Map<string, number>();
  const schemaManifest: Array<{ id: number; key: string; features: string[]; ir: unknown }> = [];
  for (let i = 0; i < sortedSchemaKeys.length; i++) {
    const k = sortedSchemaKeys[i];
    schemaKeyToId.set(k, i);
    // compatibility markers (M25-001-B): field order matches Rust SchemaDecl
    schemaManifest.push({
      id: i,
      key: k,
      features: featuresOf(schemas[k] as Parameters<typeof featuresOf>[0]),
      ir: schemas[k],
    });
  }

  // M24-005-A: canonical header-name table — security scheme headers plus
  // headers-binding schema properties, sorted and deduped across all routes.
  const headerNameSet = new Set<string>();
  const headerNamesFor = (r: (typeof app.routes)[number]): string[] => {
    const names = new Set<string>();
    const declared = (r as { security?: Array<{ header: string }> }).security;
    if (declared) {
      for (const sec of declared) names.add(sec.header);
    } else if (r.policyId) {
      names.add("authorization");
    }
    for (const n of names) headerNameSet.add(n);
    return [...names].sort();
  };
  const routeHeaderNames = app.routes.map(headerNamesFor);
  const headerNameTable = [...headerNameSet].sort();
  // M24-006-A: compile declared query object fields into canonical dense IDs.
  // Cookie bindings are not yet part of authoring contract, so cookie table
  // remains empty until its dedicated packet adds the binding surface.
  const queryNameSet = new Set<string>();
  const routeQueryNames = app.routes.map((r) => {
    const names = r.queryIr && r.queryIr.kind === "object"
      ? Object.keys((r.queryIr as { properties?: Record<string, unknown> }).properties ?? {}).sort()
      : [];
    for (const name of names) queryNameSet.add(name);
    return names;
  });
  const queryNameTable = [...queryNameSet].sort();

  const packRoutes = app.routes.map((r, routeIdx) => {
    const decision = selectRouteStrategies(r);
    // M26-007-A: status-key order is canonical (numeric ascending), never
    // source-literal order — the fallback default status is the LOWEST
    // declared status when 200 is absent, so authoring order cannot change
    // compiled output.
    const sortedStatusKeys = Object.keys(r.responses)
      .map((k) => Number(k))
      .filter((n) => !isNaN(n))
      .sort((a, b) => a - b)
      .map((n) => String(n));
    const defaultStatus = sortedStatusKeys.includes("200")
      ? 200
      : Number(sortedStatusKeys[0] ?? 200);
    const allowedStatuses = sortedStatusKeys.map((k) => Number(k));
    const responseStrategy = decision.primaryResponseStrategy;

    const paramsSchemaKey = r.paramsIr ? `sch:${r.id}.params` : null;
    const querySchemaKey = r.queryIr ? `sch:${r.id}.query` : null;
    const bodySchemaKey = r.bodyIr ? `sch:${r.id}.body` : null;

    const plan = {
      routeId: routeIdx,
      handlerId: routeIdx,
      policyId: r.policyId ? (policyIdMap.get(r.policyId) ?? null) : null,
      policyHandlerId: r.policyId ? (policyHandlerMap.get(r.policyId) ?? null) : null,
      paramsSchemaId: paramsSchemaKey ? (schemaKeyToId.get(paramsSchemaKey) ?? null) : null,
      querySchemaId: querySchemaKey ? (schemaKeyToId.get(querySchemaKey) ?? null) : null,
      headersSchemaId: null,
      bodySchemaId: bodySchemaKey ? (schemaKeyToId.get(bodySchemaKey) ?? null) : null,
      headerNameIds: routeHeaderNames[routeIdx].map((n) => headerNameTable.indexOf(n)),
      queryNameIds: routeQueryNames[routeIdx].map((n) => queryNameTable.indexOf(n)),
      cookieNameIds: [],
      defaultStatus,
      allowedStatuses,
      fieldNeeds: {
        params: r.paramsIr != null,
        query: r.queryIr != null,
        headers: r.policyId != null,
        body: r.bodyIr != null,
      },
      responseStrategy,
      // M25-007-A: fallback reasons travel with the plan — the runtime
      // rejects a js strategy without a reason from the closed vocabulary
      // (fallback never activates silently)
      ...(decision.validationStrategy === "js"
        ? {
            validationFallbackReason:
              decision.fallbacks.find((f) => ["body", "query", "params"].includes(f.location))?.reason ?? "explicit",
          }
        : {}),
      ...(responseStrategy === "js"
        ? {
            responseFallbackReason:
              decision.fallbacks.find((f) => f.location.startsWith("response."))?.reason ?? "explicit",
          }
        : {}),
      deadlineMs: 5000,
    };

    return {
      id: r.id,
      moduleId: r.moduleId,
      method: r.method,
      path: r.path,
      pathSegments: segsFor(r.path),
      handler: r.id,
      policy: r.policyId ?? null,
      params: r.paramsIr ? { schema: `sch:${r.id}.params`, coerce: "path", contentType: null, limitBytes: 0 } : null,
      query: r.queryIr ? { schema: `sch:${r.id}.query`, coerce: "query", contentType: null, limitBytes: 0 } : null,
      body: r.bodyIr
        ? { schema: `sch:${r.id}.body`, coerce: null, contentType: "application/json", limitBytes: 65536 }
        : null,
      headers: null,
      responses: Object.fromEntries(
        // M26-007-A: canonical key order in serialized output
        sortedStatusKeys.map((k) => {
          const v = r.responses[k] as { ir?: unknown; strategy?: string; problem?: unknown };
          return [
            k,
            {
              schema: v.ir && !v.problem ? `sch:${r.id}.${k}` : null,
              strategy: decision.responseStrategies[k] ?? v.strategy ?? "native",
              problem: v.problem ?? null,
            },
          ];
        }),
      ),
      validationStrategy: decision.validationStrategy,
      nativeLiveness: r.liveness,
      security: r.policyId ? [{ scheme: "bearer", header: "authorization", problemStatus: 401 }] : [],
      capabilities: r.capabilities,
      deadlineMs: 5000,
      plan,
    };
  });
  const functions = [
    ...app.routes.map((r, i) => ({
      id: i,
      key: r.id,
      kind: "route-handler",
    })),
    ...app.policies.map((p, i) => ({
      id: app.routes.length + i,
      key: p.id,
      kind: "policy-handler",
    })),
  ];

  const router = buildSerializedRouter(packRoutes);
  const canonical = rustCanonical(
    packRoutes,
    schemas,
    policyPacks,
    capabilities,
    functions,
    schemaManifest,
    policyManifest,
    router,
  );

  // G0-r1 (C): PUBLIC-ONLY contract hash. Mirrors Rust
  // public_contract_canonical_json exactly:
  // [routes, reachable-schemas(BTreeMap sorted, IR-aware sort), policies-sans-handler]
  const projectBinding = (b: { schema: string | null; coerce: string | null; contentType: string | null; limitBytes: number } | null) =>
    b ? { schema: b.schema, coerce: b.coerce, contentType: b.contentType, limitBytes: b.limitBytes } : null;
  const usedSchemas = new Set<string>();
  const publicRoutes = packRoutes.map((r) => {
    const responsesSorted: Record<string, unknown> = {};
    for (const k of Object.keys(r.responses).sort()) {
      const d = r.responses[k];
      if (d.schema) usedSchemas.add(d.schema);
      responsesSorted[k] = { schema: d.schema, problem: d.problem }; // NO strategy
    }
    for (const b of [r.params, r.query, r.headers, r.body]) {
      if (b?.schema) usedSchemas.add(b.schema);
    }
    return {
      id: r.id,
      method: r.method,
      path: r.path,
      params: projectBinding(r.params),
      query: projectBinding(r.query),
      headers: projectBinding(r.headers),
      body: projectBinding(r.body),
      responses: responsesSorted,
      security: r.security,
    };
  });
  const schemasPublic: Record<string, unknown> = {};
  for (const k of Object.keys(schemas).sort()) {
    if (usedSchemas.has(k)) schemasPublic[k] = sortIR(schemas[k]);
  }
  const policiesPublic: Record<string, unknown> = {};
  for (const k of Object.keys(policyPacks).sort()) {
    const p = policyPacks[k] as { declaredStatuses: unknown; provides: unknown };
    policiesPublic[k] = { declaredStatuses: p.declaredStatuses, provides: p.provides }; // NO handler
  }
  // M25-001-C: whole public-contract view canonicalized (sorted keys), matching
  // q_pack::public_contract_canonical_json
  const publicContractCanonical = JSON.stringify(sortIR([publicRoutes, schemasPublic, policiesPublic]));
  const contractHash = sha(publicContractCanonical).slice(0, 32);

  const pack = {
    formatVersion: 1,
    kind: "velqu.qpack",
    runtimeAbi: 1,
    executionMode: "numeric",
    // M26-002-A: the full runtime fingerprint travels with the pack —
    // rquickjs version and the runtime build hash (sha256 over the
    // runtime identity tuple, mirroring q-pack runtime_build_hash)
    engine: {
      name: "quickjs-ng",
      version: "0.15.1",
      binding: "rquickjs-0.12.2",
      rquickjs: "0.12.2",
      buildHash: runtimeBuildHash(),
    },
    schemaIrVersion: 2,
    contractVersion: 1,
    contractHash,
    builtBy: { compiler: meta.compilerVersion, typescript: meta.typescriptVersion, bun: Bun.version },
    appId: app.appId,
    modules: app.modules,
    entry: "app.js",
    bundle: bundle.code,
    // ADR-0027: production packs embed no source map; debug sources and
    // maps move to the external <pack>.sources.json sidecar (written by
    // buildApp) that the runtime never reads.
    sourceMap: null,
    routes: packRoutes,
    // M26-007-A: schemas embedded in canonical (sorted) key order — the
    // manifest IDs already derive from sorted keys; byte-identical builds
    // must not depend on registry insertion order.
    schemas: Object.fromEntries(sortedSchemaKeys.map((k) => [k, schemas[k]])),
    policies: policyPacks,
    capabilities,
    // M26-002-A: capability-set hash (mirrors q-pack capability_hash)
    capabilityHash: capabilitySetHash(capabilities),
    functions,
    schemaManifest,
    headerNameTable,
    queryNameTable,
    cookieNameTable: [],
    policyManifest,
    router,
    integrity: { algorithm: "sha256", bundleSha256: sha(bundle.code), routesSha256: sha(canonical) },
  };
  return { packJson: JSON.stringify(pack), pack };
}

// ---------------------------------------------------------------- contract + d.ts + openapi

export function tsTypeOfIr(ir: Record<string, unknown>): string {
  switch (ir.kind) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "literal": return JSON.stringify(ir.value);
    case "enum": return (ir.values as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
    case "optional": return tsTypeOfIr(ir.inner as Record<string, unknown>);
    case "nullable": return `${tsTypeOfIr(ir.inner as Record<string, unknown>)} | null`;
    case "array": return `Array<${tsTypeOfIr(ir.items as Record<string, unknown>)}>`;
    case "object": {
      const props = ir.properties as Record<string, Record<string, unknown>>;
      const req = ir.required as string[];
      const fields = Object.entries(props).map(([k, v]) =>
        req.includes(k) ? `${k}: ${tsTypeOfIr(v)}` : `${k}?: ${tsTypeOfIr(v)}`,
      );
      return `{ ${fields.join("; ")} }`;
    }
    case "union":
      return (ir.members as Record<string, unknown>[]).map(tsTypeOfIr).join(" | ");
    case "transform":
      return tsTypeOfIr(ir.output as Record<string, unknown>);
    case "file":
      return "Uint8Array";
    case "problem": {
      // M25-006-C: explicit s.problem responses are the full RFC 9457
      // envelope on the wire (M25-006-A) — the declared literals narrow
      const detail = ir.detail as Record<string, unknown> | undefined;
      const fields = [
        ir.typeUri !== undefined ? `type: "${ir.typeUri}"` : "type: string",
        `title: "${ir.title}"`,
        `status: ${ir.status}`,
        "instance: string",
      ];
      if (detail) fields.push(`detail?: ${tsTypeOfIr(detail)}`);
      return `{ ${fields.join("; ")} }`;
    }
    case "fallback":
      return ir.inner !== undefined ? tsTypeOfIr(ir.inner as Record<string, unknown>) : "unknown";
    default:
      return "unknown";
  }
}

export function contractDts(app: ExtractedApp, contractHash: string): string {
  const lines: string[] = [
    "// @generated by @velqu/compiler — published compact contract (TRT-006)",
    "// Client repositories import ONLY this file; never server source.",
    'import type { RouteContract } from "@velqu/contract";',
    "",
    `export interface Api {`,
  ];
  for (const r of app.routes) {
    const respTs = Object.entries(r.responses).map(([status, decl]) => {
      if (decl.problem) return problemTypeOf(decl.problem, status);
      if (decl.ir) return tsTypeOfIr(decl.ir);
      return "Record<string, unknown>";
    }).map((t, i) => `  ${Object.keys(r.responses)[i]}: ${t}`);
    lines.push(
      `  "${r.id}": RouteContract<`,
      `    "${r.path}",`,
      `    "${r.method}",`,
      `    ${r.paramsIr ? tsTypeOfIr(r.paramsIr) : "Record<string, never>"},`,
      `    ${r.queryIr ? tsTypeOfIr(r.queryIr) : "Record<string, never>"},`,
      `    ${r.bodyIr ? tsTypeOfIr(r.bodyIr) : "undefined"},`,
      `    {`,
      ...respTs.map((t) => `      ${t},`),
      `  }>;`,
    );
  }
  lines.push("};", "", `export const contractHash = "${contractHash}";`, "");
  return lines.join("\n");
}

/**
 * Exact runtime problem envelope per registry id (M25-006-C). The URIs and
 * titles are the frozen URNs from the pack-format spec (mirroring the
 * q-runtime registry); the status literal is the DECLARED response status,
 * so Treaty error narrowing is exact: `if (r.error.status === 401)` types
 * `r.error.problem` as the full unauthorized envelope.
 */
export const PROBLEM_REGISTRY: Record<string, { typeUri: string; title: string }> = {
  validation: { typeUri: "https://velqu.dev/problems/validation", title: "Validation failed" },
  unauthorized: { typeUri: "https://velqu.dev/problems/unauthorized", title: "Unauthorized" },
  "not-found": { typeUri: "https://velqu.dev/problems/not-found", title: "Not Found" },
  method: { typeUri: "https://velqu.dev/problems/method", title: "Method Not Allowed" },
  body: { typeUri: "https://velqu.dev/problems/body", title: "Unsupported body" },
  limit: { typeUri: "https://velqu.dev/problems/limit", title: "Payload too large" },
  timeout: { typeUri: "https://velqu.dev/problems/timeout", title: "Handler deadline exceeded" },
  overload: { typeUri: "https://velqu.dev/problems/overload", title: "Overloaded" },
  internal: { typeUri: "https://velqu.dev/problems/internal", title: "Internal Server Error" },
};

function problemTypeOf(problemId: string, status: string): string {
  const entry = PROBLEM_REGISTRY[problemId] ?? PROBLEM_REGISTRY.internal;
  const members = [
    `type: "${entry.typeUri}"`,
    `title: "${entry.title}"`,
    `status: ${status}`,
    "instance: string",
    "detail?: string",
  ];
  if (problemId === "validation") {
    members.push("errors?: { path: string; code: string; message: string }[]");
  }
  return `{ ${members.join("; ")} }`;
}

/**
 * JSON-Schema form of the same envelope (M25-006-C guardrail: OpenAPI
 * problem schemas match runtime). Required members mirror the runtime
 * builder exactly; enum-constrained type/title/status make generated
 * clients narrow identically to Treaty.
 */
function problemSchemaFor(problemId: string, status: string): Record<string, unknown> {
  const entry = PROBLEM_REGISTRY[problemId] ?? PROBLEM_REGISTRY.internal;
  const properties: Record<string, unknown> = {
    type: { type: "string", enum: [entry.typeUri] },
    title: { type: "string", enum: [entry.title] },
    status: { type: "integer", enum: [Number(status)] },
    instance: { type: "string" },
    detail: { type: "string" },
  };
  if (problemId === "validation") {
    properties.errors = {
      type: "array",
      items: {
        type: "object",
        required: ["path", "code", "message"],
        properties: {
          path: { type: "string" },
          code: { type: "string" },
          message: { type: "string" },
        },
      },
    };
  }
  return {
    type: "object",
    required: ["type", "title", "status", "instance"],
    properties,
  };
}

export function openapiFor(app: ExtractedApp): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  const components: Record<string, Record<string, unknown>> = {};
  const irToSchema = (ir: Record<string, unknown> | null, name: string): unknown => {
    if (!ir) return undefined;
    const conv = (v: Record<string, unknown>): Record<string, unknown> => {
      const out: Record<string, unknown> = { type: v.kind === "integer" || v.kind === "number" ? v.kind === "integer" ? "integer" : "number" : v.kind };
      if (v.kind === "string") {
        if (v.minLength !== undefined) out.minLength = v.minLength;
        if (v.maxLength !== undefined) out.maxLength = v.maxLength;
        if (v.pattern !== undefined) out.pattern = v.pattern;
        if (v.format !== undefined) out.format = v.format;
      }
      if (v.kind === "integer" || v.kind === "number") {
        if (v.minimum !== undefined) out.minimum = v.minimum;
        if (v.maximum !== undefined) out.maximum = v.maximum;
      }
      if (v.kind === "array") out.items = conv(v.items as Record<string, unknown>);
      if (v.kind === "enum") { out.type = "string"; out.enum = v.values; }
      if (v.kind === "literal") { out.type = typeof v.value; out.enum = [v.value]; }
      if (v.kind === "union") {
        out.type = undefined;
        out.oneOf = (v.members as Record<string, unknown>[]).map(conv);
      }
      if (v.kind === "transform") return conv(v.output as Record<string, unknown>);
      if (v.kind === "file") {
        return { type: "string", format: "binary", "x-maxBytes": v.maxBytes, ...(v.contentType !== undefined ? { "x-contentType": v.contentType } : {}) };
      }
      if (v.kind === "problem") {
        const detail = v.detail as Record<string, unknown> | undefined;
        const props: Record<string, unknown> = { title: { type: "string" }, status: { type: "integer" } };
        if (detail) props.detail = conv(detail);
        return {
          type: "object",
          properties: props,
          required: ["title", "status"],
          "x-problem": { ...(v.typeUri !== undefined ? { typeUri: v.typeUri } : {}), title: v.title, status: v.status },
        };
      }
      if (v.kind === "fallback") {
        // explicit fallback stays visible in the projection (ADR-0009)
        return v.inner !== undefined
          ? { ...conv(v.inner as Record<string, unknown>), "x-fallback": v.reason }
          : { "x-fallback": v.reason };
      }
      if (v.kind === "optional" || v.kind === "nullable") return conv(v.inner as Record<string, unknown>);
      if (v.kind === "object") {
        out.type = "object";
        const props: Record<string, unknown> = {};
        for (const [k, p] of Object.entries(v.properties as Record<string, Record<string, unknown>>)) {
          props[k] = conv(p);
        }
        out.properties = props;
        out.required = v.required;
        out.additionalProperties = false;
      }
      return out;
    };
    const schema = conv(ir);
    components[name] = { ...schema } as Record<string, unknown>;
    return { $ref: `#/components/schemas/${name}` };
  };

  for (const r of app.routes) {
    const params = (r.path.match(/:[A-Za-z]+/g) ?? []).map((p) => p.slice(1));
    const op: Record<string, unknown> = {
      operationId: r.id,
      responses: Object.fromEntries(
        Object.entries(r.responses).map(([status, decl]) => [
          status,
          {
            description: decl.problem ? `problem: ${decl.problem}` : "success",
            content:
              decl.ir && !decl.problem
                ? { "application/json": { schema: irToSchema(decl.ir, `${r.id}.resp${status}`) } }
                : decl.problem
                  ? { "application/problem+json": { schema: problemSchemaFor(decl.problem, status) } }
                  : undefined,
          },
        ]),
      ),
    };
    if (params.length || r.paramsIr) {
      op.parameters = params.map((p) => ({
        name: p,
        in: "path",
        required: true,
        schema: { type: "string" },
      }));
    }
    if (r.queryIr) {
      op.parameters = [
        ...((op.parameters as unknown[]) ?? []),
        ...Object.keys((r.queryIr as { properties?: Record<string, unknown> }).properties ?? {}).map((k) => ({
          name: k,
          in: "query",
          required: ((r.queryIr as { required?: string[] }).required ?? []).includes(k),
          schema: { type: "string" },
        })),
      ];
    }
    if (r.bodyIr) {
      op.requestBody = {
        required: true,
        content: { "application/json": { schema: irToSchema(r.bodyIr, `${r.id}.body`) } },
      };
    }
    if (r.policyId) op.security = [{ bearerAuth: [] }];
    const oaPath = r.path.replace(/:([A-Za-z]+)/g, "{$1}");
    (paths[oaPath] ??= {})[r.method.toLowerCase()] = op;
  }
  return {
    openapi: "3.1.0",
    info: { title: app.appId, version: "0.1.0" },
    paths,
    components: {
      schemas: components,
      securitySchemes: app.policies.length ? { bearerAuth: { type: "http", scheme: "bearer" } } : undefined,
    },
  };
}

// ---------------------------------------------------------------- semantic diff

export interface DiffEntry {
  routeId: string;
  kind: "breaking" | "compatible" | "policy-sensitive";
  change: string;
}

export function diffContracts(current: Record<string, unknown>, lock: Record<string, unknown>): DiffEntry[] {
  const out: DiffEntry[] = [];
  const cur = current.routes as Record<string, Record<string, unknown>>;
  const prev = lock.routes as Record<string, Record<string, unknown>>;

  for (const [id, route] of Object.entries(cur)) {
    if (!prev[id]) {
      out.push({ routeId: id, kind: "compatible", change: "route added" });
      continue;
    }
    const p = prev[id];
    if (p.path !== route.path) {
      out.push({ routeId: id, kind: "breaking", change: `path changed ${p.path} → ${route.path}` });
    }
    if (p.method !== route.method) {
      out.push({ routeId: id, kind: "breaking", change: `method changed ${p.method} → ${route.method}` });
    }

    // Status codes diff
    const prevResponses = (p.responses ?? {}) as Record<string, unknown>;
    const curResponses = (route.responses ?? {}) as Record<string, unknown>;
    const prevStatuses = Array.isArray(prevResponses) ? prevResponses : Object.keys(prevResponses);
    const curStatuses = Array.isArray(curResponses) ? curResponses : Object.keys(curResponses);

    for (const s of prevStatuses) {
      if (!curStatuses.includes(s)) {
        out.push({ routeId: id, kind: "breaking", change: `response status ${s} removed` });
      }
    }
    for (const s of curStatuses) {
      if (!prevStatuses.includes(s)) {
        const is2xx = Number(s) >= 200 && Number(s) < 300;
        out.push({
          routeId: id,
          kind: is2xx ? "compatible" : "policy-sensitive",
          change: `response status ${s} added`,
        });
      }
    }

    // Security diff
    const prevSec = p.security ?? null;
    const curSec = route.security ?? null;
    if (prevSec !== curSec) {
      if (!prevSec && curSec) {
        out.push({
          routeId: id,
          kind: "breaking",
          change: `security policy added (${JSON.stringify(curSec)}) — requires authentication`,
        });
      } else if (prevSec && !curSec) {
        out.push({
          routeId: id,
          kind: "policy-sensitive",
          change: `security policy removed (${JSON.stringify(prevSec)}) — endpoint became unauthenticated`,
        });
      } else {
        out.push({
          routeId: id,
          kind: "policy-sensitive",
          change: `security policy changed ${JSON.stringify(prevSec)} → ${JSON.stringify(curSec)}`,
        });
      }
    }

    // Input Schema Diff (params, query, body)
    diffSchemaSection(id, "params", p.params as Record<string, unknown> | null, route.params as Record<string, unknown> | null, out, true);
    diffSchemaSection(id, "query", p.query as Record<string, unknown> | null, route.query as Record<string, unknown> | null, out, true);
    diffSchemaSection(id, "body", p.body as Record<string, unknown> | null, route.body as Record<string, unknown> | null, out, true);

    // Response Schema Diff for common 2xx responses
    if (!Array.isArray(prevResponses) && !Array.isArray(curResponses)) {
      for (const s of curStatuses) {
        if (prevStatuses.includes(s) && Number(s) >= 200 && Number(s) < 300) {
          diffSchemaSection(
            id,
            `response.${s}`,
            prevResponses[s] as Record<string, unknown> | null,
            curResponses[s] as Record<string, unknown> | null,
            out,
            false,
          );
        }
      }
    }
  }

  for (const id of Object.keys(prev)) {
    if (!cur[id]) {
      out.push({ routeId: id, kind: "breaking", change: "route removed" });
    }
  }
  return out;
}

function diffSchemaSection(
  routeId: string,
  section: string,
  prev: Record<string, unknown> | null,
  cur: Record<string, unknown> | null,
  out: DiffEntry[],
  isInput: boolean,
) {
  if (!prev && !cur) return;
  if (!prev && cur) {
    const req = (cur.required as string[]) ?? [];
    if (isInput && req.length > 0) {
      out.push({ routeId, kind: "breaking", change: `${section}: added required schema with required fields [${req.join(", ")}]` });
    } else {
      out.push({ routeId, kind: "compatible", change: `${section}: schema added` });
    }
    return;
  }
  if (prev && !cur) {
    out.push({ routeId, kind: isInput ? "compatible" : "breaking", change: `${section}: schema removed` });
    return;
  }
  if (prev && cur) {
    diffSchemaTypes(routeId, section, prev, cur, out, isInput);
  }
}

function diffSchemaTypes(
  routeId: string,
  section: string,
  prev: Record<string, unknown>,
  cur: Record<string, unknown>,
  out: DiffEntry[],
  isInput: boolean,
) {
  if (prev.kind !== cur.kind) {
    out.push({
      routeId,
      kind: "breaking",
      change: `${section}: type kind changed ${prev.kind} → ${cur.kind}`,
    });
    return;
  }
  if (prev.kind === "object" && cur.kind === "object") {
    const prevProps = (prev.properties ?? {}) as Record<string, Record<string, unknown>>;
    const curProps = (cur.properties ?? {}) as Record<string, Record<string, unknown>>;
    const prevReq = new Set((prev.required as string[]) ?? []);
    const curReq = new Set((cur.required as string[]) ?? []);

    for (const [propName, curProp] of Object.entries(curProps)) {
      if (!prevProps[propName]) {
        const isRequired = curReq.has(propName);
        if (isInput) {
          out.push({
            routeId,
            kind: isRequired ? "breaking" : "compatible",
            change: `${section}.${propName}: ${isRequired ? "required" : "optional"} field added to input`,
          });
        } else {
          out.push({
            routeId,
            kind: "compatible",
            change: `${section}.${propName}: field added to response`,
          });
        }
      } else {
        const prevProp = prevProps[propName];
        if (isInput && !prevReq.has(propName) && curReq.has(propName)) {
          out.push({
            routeId,
            kind: "breaking",
            change: `${section}.${propName}: optional input field became required`,
          });
        }
        diffSchemaTypes(routeId, `${section}.${propName}`, prevProp, curProp, out, isInput);
      }
    }

    for (const propName of Object.keys(prevProps)) {
      if (!curProps[propName]) {
        if (isInput) {
          out.push({ routeId, kind: "compatible", change: `${section}.${propName}: input field removed` });
        } else {
          out.push({ routeId, kind: "breaking", change: `${section}.${propName}: response field removed` });
        }
      }
    }
  } else if (prev.kind === "array" && cur.kind === "array") {
    // M25-008-D: IR v2 scalar constraints participate in the diff
    diffBounds(routeId, section, prev, cur, "minItems", "maxItems", out, isInput);
    if (prev.items && cur.items) {
      diffSchemaTypes(routeId, `${section}[]`, prev.items as Record<string, unknown>, cur.items as Record<string, unknown>, out, isInput);
    }
  } else if (prev.kind === "string" && cur.kind === "string") {
    diffBounds(routeId, section, prev, cur, "minLength", "maxLength", out, isInput);
    diffAdded(routeId, section, prev, cur, "pattern", out, isInput);
    diffAdded(routeId, section, prev, cur, "format", out, isInput);
  } else if (
    (prev.kind === "integer" || prev.kind === "number") &&
    (cur.kind === "integer" || cur.kind === "number")
  ) {
    diffBounds(routeId, section, prev, cur, "minimum", "maximum", out, isInput);
  } else if (prev.kind === "enum" && cur.kind === "enum") {
    const removed = ((prev.values as unknown[]) ?? []).filter(
      (v) => !((cur.values as unknown[]) ?? []).includes(v),
    );
    if (removed.length > 0) {
      out.push({
        routeId,
        kind: isInput ? "breaking" : "compatible",
        change: `${section}: enum value(s) removed [${removed.map((v) => JSON.stringify(v)).join(", ")}]`,
      });
    }
  } else if (prev.kind === "literal" && cur.kind === "literal") {
    if (JSON.stringify(prev.value) !== JSON.stringify(cur.value)) {
      out.push({
        routeId,
        kind: "breaking",
        change: `${section}: literal changed ${JSON.stringify(prev.value)} → ${JSON.stringify(cur.value)}`,
      });
    }
  } else if (prev.kind === "union" && cur.kind === "union") {
    const curMembers = (cur.members as Record<string, unknown>[]).map((m) =>
      JSON.stringify(canonicalIr(m)),
    );
    const removed = (prev.members as Record<string, unknown>[]).filter(
      (m) => !curMembers.includes(JSON.stringify(canonicalIr(m))),
    );
    if (removed.length > 0) {
      out.push({
        routeId,
        kind: isInput ? "breaking" : "compatible",
        change: `${section}: ${removed.length} union member(s) removed`,
      });
    }
  } else if (prev.kind === "nullable" && cur.kind === "nullable") {
    diffSchemaTypes(routeId, section, prev.inner as Record<string, unknown>, cur.inner as Record<string, unknown>, out, isInput);
  } else if (prev.kind === "optional" && cur.kind === "optional") {
    diffSchemaTypes(routeId, section, prev.inner as Record<string, unknown>, cur.inner as Record<string, unknown>, out, isInput);
  } else if (prev.kind === "fallback" && cur.kind === "fallback") {
    if (prev.reason !== cur.reason) {
      out.push({
        routeId,
        kind: "policy-sensitive",
        change: `${section}: fallback reason changed ${prev.reason} → ${cur.reason} (codec path change)`,
      });
    }
    if (prev.inner && cur.inner) {
      diffSchemaTypes(routeId, section, prev.inner as Record<string, unknown>, cur.inner as Record<string, unknown>, out, isInput);
    }
  }
}

/** M25-008-D: numeric-ish bounds (min/max, lengths, item counts). */
function diffBounds(
  routeId: string,
  section: string,
  prev: Record<string, unknown>,
  cur: Record<string, unknown>,
  minKey: string,
  maxKey: string,
  out: DiffEntry[],
  isInput: boolean,
) {
  const prevMin = prev[minKey] as number | undefined;
  const curMin = cur[minKey] as number | undefined;
  const prevMax = prev[maxKey] as number | undefined;
  const curMax = cur[maxKey] as number | undefined;

  // tightening: a floor appears or rises, a ceiling appears or falls —
  // previously-accepted input now rejects (breaking); responses narrow
  // (policy-sensitive: clients may receive narrower data than typed)
  const minTightened = curMin !== undefined && (prevMin === undefined || curMin > prevMin);
  const maxTightened = curMax !== undefined && (prevMax === undefined || curMax < prevMax);
  if (minTightened || maxTightened) {
    out.push({
      routeId,
      kind: isInput ? "breaking" : "policy-sensitive",
      change: `${section}: bounds tightened (${minKey}: ${prevMin ?? "—"} → ${curMin ?? "—"}, ${maxKey}: ${prevMax ?? "—"} → ${curMax ?? "—"})`,
    });
  }

  // loosening: a floor falls/disappears or a ceiling rises/disappears —
  // input accepts more (compatible); responses may carry wider data
  const minLoosened = prevMin !== undefined && (curMin === undefined || curMin < prevMin);
  const maxLoosened = prevMax !== undefined && (curMax === undefined || curMax > prevMax);
  if (minLoosened || maxLoosened) {
    out.push({
      routeId,
      kind: "compatible",
      change: `${section}: bounds loosened (${minKey}: ${prevMin ?? "—"} → ${curMin ?? "—"}, ${maxKey}: ${prevMax ?? "—"} → ${curMax ?? "—"})`,
    });
  }
}

/** M25-008-D: a scalar constraint member appearing/changing/vanishing. */
function diffAdded(
  routeId: string,
  section: string,
  prev: Record<string, unknown>,
  cur: Record<string, unknown>,
  key: string,
  out: DiffEntry[],
  isInput: boolean,
) {
  if (prev[key] === undefined && cur[key] !== undefined) {
    out.push({
      routeId,
      kind: isInput ? "breaking" : "policy-sensitive",
      change: `${section}: ${key} constraint added (${JSON.stringify(cur[key])})`,
    });
  } else if (prev[key] !== undefined && cur[key] === undefined) {
    out.push({
      routeId,
      kind: "compatible",
      change: `${section}: ${key} constraint removed`,
    });
  } else if (prev[key] !== cur[key]) {
    out.push({
      routeId,
      kind: isInput ? "breaking" : "policy-sensitive",
      change: `${section}: ${key} changed ${JSON.stringify(prev[key])} → ${JSON.stringify(cur[key])}`,
    });
  }
}

/** Canonical member form for union comparison (sorted keys). */
function canonicalIr(ir: Record<string, unknown>): Record<string, unknown> {
  return Object.keys(ir)
    .sort()
    .reduce<Record<string, unknown>>((acc, k) => {
      acc[k] = ir[k];
      return acc;
    }, {});
}
