[package]
name = "q-pack"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
q-engine = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
q-schema-runtime = { workspace = true }
